export interface Note {
  id: string;
  timePoint: number; // in seconds
  content: string;
  createdAt: number; // timestamp
}

export interface SummaryItem {
  timePoint: number; // in seconds
  content: string;
}

export interface AISummary {
  title: string; // Personalized title generated by LLM
  items: SummaryItem[];
}

export interface PodcastData {
  audioUrl: string;
  title?: string;
  description?: string;
  shownotes?: string;
  intro?: string; // Content before 【内容提要】
  summaryNotes?: SummaryItem[]; // Content after 【内容提要】 with time points
  summaries?: {
    summary1?: AISummary;
    summary2?: AISummary;
    summary3?: AISummary;
  };
  transcript?: string;
}

export interface Comment {
  id: string;
  timePoint: number; // in seconds
  content: string;
  createdAt: number; // timestamp
}

export type SortOption = 'time' | 'newest' | 'oldest';

export type SummaryTab = 'original' | 'summary1' | 'summary2' | 'summary3';

export type RightTab = 'notes' | 'transcripts' | 'comments';

export type TranslationLanguage = 
  | 'original' 
  | 'chinese' 
  | 'english' 
  | 'japanese' 
  | 'korean' 
  | 'spanish' 
  | 'french';

